[tool.poetry]
name = "git-good"
version = "0.1.0"
description = ""
authors = ["ceilingrat <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
asciinema = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
